export const cases = [
  { name: 'add nested file', before: {}, patch: '*** Add File: nested/a\n+hello', after: { 'nested/a': 'hello\n' } },
  { name: 'delete', before: { a: 'old\n' }, patch: '*** Delete File: a', after: {} },
  { name: 'replace', before: { a: 'old\n' }, patch: '*** Update File: a\n@@\n-old\n+new', after: { a: 'new\n' } },
  { name: 'first chunk without header', before: { a: 'old\n' }, patch: '*** Update File: a\n-old\n+new', after: { a: 'new\n' } },
  { name: 'multiple hunks', before: { a: 'a\nb\nc\nd\n' }, patch: '*** Update File: a\n@@\n-a\n+A\n@@\n-d\n+D', after: { a: 'A\nb\nc\nD\n' } },
  { name: 'text anchor', before: { a: 'first\nx\nsecond\nx\n' }, patch: '*** Update File: a\n@@ second\n-x\n+y', after: { a: 'first\nx\nsecond\ny\n' } },
  { name: 'EOF selects last occurrence', before: { a: 'x\nx\n' }, patch: '*** Update File: a\n@@\n-x\n+y\n*** End of File', after: { a: 'x\ny\n' } },
  { name: 'append', before: { a: 'a\n' }, patch: '*** Update File: a\n@@\n+b', after: { a: 'a\nb\n' } },
  { name: 'insertion with context', before: { a: 'a\nb\n' }, patch: '*** Update File: a\n@@\n a\n+x\n b', after: { a: 'a\nx\nb\n' } },
  { name: 'deletion only', before: { a: 'a\nb\n' }, patch: '*** Update File: a\n@@\n-a\n b', after: { a: 'b\n' } },
  { name: 'move and edit', before: { a: 'old\n' }, patch: '*** Update File: a\n*** Move to: nested/b\n@@\n-old\n+new', after: { 'nested/b': 'new\n' } },
  { name: 'Unicode and literal dollars', before: { a: 'héllo\n' }, patch: '*** Update File: a\n@@\n-héllo\n+κόσμος $$ $&', after: { a: 'κόσμος $$ $&\n' } },
  { name: 'BOM', before: { a: '\uFEFFold\n' }, patch: '*** Update File: a\n@@\n-old\n+new', after: { a: '\uFEFFnew\n' } },
  { name: 'CRLF', before: { a: 'a\r\nb\r\n' }, patch: '*** Update File: a\n@@\n-b\n+B', after: { a: 'a\r\nB\r\n' } },
  { name: 'mixed endings preserve context', before: { a: 'a\r\nb\nc\r\n' }, patch: '*** Update File: a\n@@\n a\n-b\n+B\n c', after: { a: 'a\r\nB\r\nc\r\n' } },
  { name: 'no final newline stays absent', before: { a: 'old' }, patch: '*** Update File: a\n@@\n-old\n+new', after: { a: 'new' } },
  { name: 'empty file append', before: { a: '' }, patch: '*** Update File: a\n@@\n+x', after: { a: 'x\n' } },
  { name: 'empty add', before: {}, patch: '*** Add File: a', after: { a: '' } },
  { name: 'batch', before: { a: 'a\n', b: 'b\n' }, patch: '*** Update File: a\n@@\n-a\n+A\n*** Delete File: b\n*** Add File: c\n+c', after: { a: 'A\n', c: 'c\n' } },
  { name: 'tabs and blank lines', before: { a: '\tx\n\nend\n' }, patch: '*** Update File: a\n@@\n-\tx\n+\ty\n \n end', after: { a: '\ty\n\nend\n' } },
] satisfies Array<{ name: string; before: Record<string, string>; patch: string; after: Record<string, string> }>;

export const rejected = [
  { name: 'ambiguous context', before: { a: 'x\nx\n' }, patch: '*** Update File: a\n@@\n-x\n+y' },
  { name: 'missing context', before: { a: 'x\n' }, patch: '*** Update File: a\n@@\n-z\n+y' },
  { name: 'indentation mismatch', before: { a: '  x\n' }, patch: '*** Update File: a\n@@\n-x\n+y' },
  { name: 'missing file', before: {}, patch: '*** Update File: a\n@@\n-x\n+y' },
  { name: 'existing add', before: { a: 'x\n' }, patch: '*** Add File: a\n+y' },
  { name: 'existing move destination', before: { a: 'x\n', b: 'b\n' }, patch: '*** Update File: a\n*** Move to: b\n@@\n-x\n+y' },
  { name: 'invalid later operation leaves earlier add unapplied', before: {}, patch: '*** Add File: a\n+x\n*** Delete File: missing' },
  { name: 'duplicate target', before: { a: 'x\n' }, patch: '*** Delete File: a\n*** Add File: a\n+y' },
  { name: 'conflicting ancestor', before: {}, patch: '*** Add File: a\n+x\n*** Add File: a/b\n+y' },
  { name: 'missing anchor', before: { a: 'x\n' }, patch: '*** Update File: a\n@@ absent\n-x\n+y' },
  { name: 'empty update', before: { a: 'x\n' }, patch: '*** Update File: a' },
  { name: 'invalid operation', before: {}, patch: '*** Frobnicate File: a' },
  { name: 'invalid content prefix', before: {}, patch: '*** Add File: a\nnot prefixed' },
  { name: 'empty batch', before: {}, patch: '' },
] satisfies Array<{ name: string; before: Record<string, string>; patch: string }>;
